#!/usr/bin/env bash

(( $# )) || { echo "usage: ${0##*/} <title> <details>"; exit 1; }

gdbus=$(command -v gdbus)
notify=$(command -v notify-send)
zenity=$(command -v zenity)
rofi=$(command -v rofi)
nagbar=$(command -v i3-nagbar)
xmessage=$(command -v xmessage)
logger=$(command -v logger)

# check if a notification daemon is running
if [[ -e ${gdbus} && -e ${notify} && $(${gdbus} call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/Dbus --method org.freedesktop.DBus.ListNames) =~ 'org.freedesktop.Notifications' ]]; then
  ${notify} --urgency=normal "${1}" "${2}"
elif [[ -e ${zenity} ]]; then
  ${zenity} --info --text "${1}:\n${2}"
elif [[ -e ${rofi} ]]; then
  ${rofi} -markup -e "<b>${1}</b>: ${2}"
elif [[ -e ${nagbar} ]]; then
  ${nagbar} -t warning -m "${1}: ${2}"
elif [[ -e ${xmessage} ]]; then
  printf "${1}\n${2}" | ${xmessage} -center -timeout 5 -file -
elif [[ -e ${logger} ]]; then
  ${logger} -t notify -- ${1}: ${2}
else
  echo "${1}: ${2}"
fi
